# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       btts-rpc-client

# >> macros
# << macros

Summary:    Bluetooth Test Suite RPC Client
Version:    0.1.0
Release:    0
Group:      Development/Testing
License:    GPLv2
URL:        https://github.com/mer-qa/btts
Source0:    %{name}-%{version}.tar.gz
Source100:  btts-rpc-client.yaml
Requires:   openssh-clients

%description
This package contains the 'bttsr' tool from Bluetooth Test Suite


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
make install-rpc-client DESTDIR=%{buildroot} DEFAULT_BTTS_HOST=%{?btts_host}
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}/bttsr
%{_sysconfdir}/bttsr/bttsr.conf
%{_sysconfdir}/bttsr/id_rsa
# >> files
# << files
