#!/bin/bash
#
# BTTS - BlueTooth Test Suite
#
# Copyright (C) 2014 Jolla Ltd.
# Contact: Martin Kampas <martin.kampas@jollamobile.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 2.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

usage()
{
  cat <<END
usage: rpc-shell

Meant to be used with SSH publickey authentication to only allow 'btts' command
execution.

Command line to execute is read from SSH_ORIGINAL_COMMAND environment variable.
Arguments must be separated with ASCII unit separator character (0x1F).
END
}

if [[ ${#*} -gt 0 ]]
then
  usage >&2
  exit 1
fi

OLD_IFS="${IFS}"
IFS=$'\x1F'
COMMAND_LINE=(${SSH_ORIGINAL_COMMAND})
IFS="${OLD_IFS}"

COMMAND_NAME="${COMMAND_LINE[0]}"
if [[ ${COMMAND_NAME} != "btts" ]]
then
  cat <<END
Command ${COMMAND_NAME:-/bin/sh} disallowed. Only 'btts' command is allowed.
END
  exit 1
fi

unset COMMAND_LINE[0]

export BTTS_RESTRICTED=1
exec /usr/bin/btts "${COMMAND_LINE[@]}"
