#!/usr/bin/python3

import argparse
import dbus
import dbus.mainloop.glib
import sys

import btts
from   btts.cliutils import failure_on, bad_usage_on, error_handler

class CommandAdapter:
    '''\
    Get/Set adapter to work with.

    Device aliases can be defined in /etc/btts/adapters.  Content of this file
    is newline separated list of records.  Each record consists of a space
    separated pair of <bd_address> and <alias>. Lines starting with "#" are
    ignored.
    '''

    def __init__(self, subparsers):
        parser = subparsers.add_parser(
                'adapter',
                help='Get/Set adapter to work with',
                formatter_class=argparse.RawDescriptionHelpFormatter,
                description=self.__doc__)
        parser.add_argument(
                'adapter', nargs='?', type=str,
                help='Device name (e.g. "hci0") or alias (see above)')
        parser.set_defaults(handler=self)

    @failure_on([btts.AdapterManager.Error])
    @bad_usage_on([btts.AdapterManager.NoSuchAdapterError])
    def __call__(self, args):
        adapter_manager = btts.AdapterManager()

        if args.adapter == None:
            print(adapter_manager.get_adapter())
        else:
            adapter_manager.set_adapter(args.adapter)

class CommandHostAlias:
    '''\
    Get/Set name to be always used by the selected adapter.

    This is the same as to access the org.bluez.Adapter1.Alias bluez5 D-Bus API
    property of the adapter selected with the `adapter' command.

    Alias of the previously selected adapter will be automatically reset prior
    to setting alias to the newly selected adapter so there is (should be)
    always just one device with the given alias available on the network. Also
    the previously selected adapter is automaticaly powered off. The newly
    selected adapter's powered state is not touched.
    '''

    def __init__(self, subparsers):
        parser = subparsers.add_parser(
                'host-alias',
                help='Get/Set name to be always used by the selected adapter',
                formatter_class=argparse.RawDescriptionHelpFormatter,
                description=self.__doc__)
        parser.add_argument(
                'alias', nargs='?', type=str,
                help='Host alias. Pass empty string to reset adapter alias.')
        parser.set_defaults(handler=self)

    @failure_on([btts.AdapterManager.Error])
    def __call__(self, args):
        adapter_manager = btts.AdapterManager()

        if args.alias == None:
            host_alias = adapter_manager.get_host_alias()
            if host_alias:
                print(host_alias)
            else:
                print('<unset>')
        else:
            adapter_manager.set_host_alias(args.alias)

class CommandDevice:
    '''\
    Get/Set the remote device to work with.
    '''

    def __init__(self, subparsers):
        parser = subparsers.add_parser(
                'device',
                help='Get/Set the remote device to work with',
                formatter_class=argparse.RawDescriptionHelpFormatter,
                description=self.__doc__)
        parser.add_argument(
                'device', nargs='?', type=str,
                help='Device address')
        parser.set_defaults(handler=self)

    @failure_on([btts.DeviceManager.Error])
    @bad_usage_on([btts.DeviceManager.InvalidAddressError])
    def __call__(self, args):
        device_manager = btts.DeviceManager()

        if args.device == None:
            print(device_manager.device_address)
        else:
            device_manager.device_address = args.device

# Main argument parser
main_parser = argparse.ArgumentParser(
        prog='btts config',
        description='Bluetooth Test Suite configuration and management utility.')
subparsers = main_parser.add_subparsers(
        dest='subcommand', title='subcommands',
        help='''Valid subcommands. Pass "<subcommand> --help" to get more help
            on the given subcommand.''')

CommandAdapter(subparsers)
CommandHostAlias(subparsers)
CommandDevice(subparsers)

args = main_parser.parse_args()
if not args.subcommand:
    main_parser.print_usage()
    sys.exit(1)

dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)

with error_handler(main_parser):
    args.handler(args)
